services:
  # =============== DATABASES & RABBITMQ ===============
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped
  # ============== MICROSERVICES ===============
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  courses-ms:
    build:
      context: ./course-service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./course-service/.env
    environment:
      ADMIN_KEY: "superKey123"
      SCRAPER_HOST: "http://scraper-ms:4004"
      SCRAPER_PENSUM_PATH: "/pensum"
      COURSES_JSON_PATH: "/app/courses.json"
      REQUEST_TIMEOUT: "300"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      EMAIL_QUEUE: "email_queue"
    depends_on:
      - scraper-ms
      - rabbitmq
    ports:
      - "8017:8000"
    volumes:
      - ./course-service:/app
    restart: unless-stopped
  email-worker:
    build: ./email-worker
    depends_on:
      - rabbitmq
      - auth-ms
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      EMAIL_QUEUE: email_queue
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: your_email@gmail.com
      SMTP_PASS: "rdmk ajua yedj rjpl"
      AUTH_SERVICE_URL: http://auth-ms:8000/api/auth/users/
      NEW_GROUP_QUEUE: new_group_notification
    restart: unless-stopped

  auth-ms:
    build:
      context: ./auth-service
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn auth_service.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: auth_service.settings
      DB_NAME: auth_db
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      DB_HOST: auth-db
      DB_PORT: "5432"
      ALLOWED_HOSTS: "*"
    depends_on:
      - auth-db
    ports:
      - "8018:8000"
    volumes:
      - ./auth-service:/app
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - courses-ms
      - auth-ms

  scraper-ms:
    build:
      context: ./scraper-service
      dockerfile: Dockerfile
    env_file:
      - ./scraper-service/.env
    ports:
      - "4004:4004"
    restart: unless-stopped

volumes:
  auth_db_data:
